# -*- coding: utf-8 -*-
"""LDUNLP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11vnbSTsmfTBVVI3Guj83SJN_EGHhA3Uk
"""

import pandas as pd 
import numpy as np

data=pd.read_csv('Language Detection.csv')

data.head()

data["Language"].value_counts()

df = data["Text"]
df1 = data["Language"]

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1 = le.fit_transform(df1)

df1

df

df.tail()

import re
import sys
li = []
# iterating through all the text
for x in df:
       
        x = re.sub(r'[!@#$(),n"%^*?:;~`0-9]', ' ', x)
        #x = re.sub(r'[]','',x)
        x = x.lower()
        li.append(x)

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
df= cv.fit_transform(li).toarray()
df.shape

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df, df1, train_size = 0.80)

from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)



def predict(text):
     x = cv.transform([text]).toarray() 
     lang = model.predict(x)
     lang = le.inverse_transform(lang) 
     print("The langauge is in",lang[0])


s=input()
predict(s)


